---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# First steps in spatial handling and visualization
**Instructors: Sébastien Rochette, Dorris Scott, Jakub Nowosad**

<!-- badges: start -->
<!-- badges: end -->

## Tutorial purpose
The tutorial is designed for R users from a variety of fields who are interested in working with spatial data and creating maps with R. No knowledge of cartography is required. Prior knowledge of (non-spatial) graphic making and data handling with the {tidyverse} in R is recommended.


## Content of this repository
- `courses/`: PDF versions of the slides.
- `data/`: Shapefiles and data used in the slides and in the exercises. These data includes a csvs file of restaurants of St. Louis and points of interest along with a boundary file of St. Louis neighborhoods.  Please consult the README document in the data folder for more information about the specific datasets. 
- `exercises/` : R markdown files of the exercises.
- `answers/`: Answers to the tutorial exercises. 


